// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.migration.version", 162);
user_pref("browser.policies.applied", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1768106700);
user_pref("browser.search.region", "ID");
user_pref("datareporting.dau.cachedUsageProfileGroupID", "3984c772-ead4-4629-a92d-0670b6b918bd");
user_pref("datareporting.dau.cachedUsageProfileID", "41a4fb4b-d496-4d56-b5ff-da537971d656");
user_pref("distribution.iniFile.exists.appversion", "146.0.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20251217121356");
user_pref("extensions.lastAppVersion", "146.0.1");
user_pref("extensions.lastPlatformVersion", "146.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"94a2091e-0dd2-4efc-ac4a-8ee116c61517\",\"formautofill@mozilla.org\":\"30d70bed-0efb-46ee-8a5d-8c9c95a2f268\",\"ipp-activator@mozilla.com\":\"f88c237f-46e6-4296-819d-17e90f07376a\",\"pictureinpicture@mozilla.org\":\"70d1df76-2d6e-45e0-86fb-f08ab00155c7\",\"addons-search-detection@mozilla.com\":\"b35828e2-b73f-4d7b-9bb0-83e51d914320\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"3c38e961-3b13-4be3-96f7-a9399cf87d5c\",\"default-theme@mozilla.org\":\"0183cb9f-c514-4d22-a45f-931852d0e892\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("pdfjs.enabledCache.state", true);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1768106698);
user_pref("toolkit.telemetry.cachedClientID", "184032ef-84c7-43ae-8797-a4ecb675e9b8");
user_pref("toolkit.telemetry.cachedProfileGroupID", "98b6947f-644f-467e-b0fa-f901078291cf");
user_pref("toolkit.telemetry.previousBuildID", "20251217121356");
